on:
  push:
    branches:
      - main

name: "Check shell script"

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master

  discord-notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: shellcheck   # attend que le job shellcheck soit terminé
    steps:
      - uses: actions/checkout@v4
      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
